# Generated by Django 4.2.20 on 2025-03-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_playlist_playlistentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="explicit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.CharField(default="Hip-Hop", max_length=50),
        ),
    ]
